default_language_version:
  python: python3.7

default_stages: [commit, push]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: format-style
        name: format-style
        entry: make format-style
        language: system

  - repo: local
    hooks:
      - id: clean
        name: clean
        entry: make clean
        language: system

  - repo: local
    hooks:
      - id: check-syntax-errors
        name: check-syntax-errors
        entry: make check-syntax-errors
        language: system

  - repo: local
    hooks:
      - id: check-safety
        name: check-safety
        entry: make check-safety
        language: system

  - repo: local
    hooks:
      - id: check-style
        name: check-style
        entry: make check-style
        language: system

  - repo: local
    hooks:
      - id: run-tests
        name: run-tests
        entry: make run-tests
        language: system
