[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=61" ]

[project]
name = "openfisca-country_template"
version = "8.0.3"
description = "OpenFisca Rules as Code model for Country-Template."
readme = "README.md"
keywords = [ "benefit", "microsimulation", "rac", "rules-as-code", "tax" ]
maintainers = [  ]
authors = [  ]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

dependencies = [
    "openfisca-core[web-api]>=43",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.6.9,<1",
    "ruff-lsp>=0.0.57,<1",
    "yamllint>=1.35.1",
]

[dependency-groups]
dev = [
    "ruff>=0.6.9,<1",
    "ruff-lsp>=0.0.57,<1",
    "yamllint>=1.35.1",
    "twine",
]

[project.urls]
Changelog = "https://github.com/openfisca/country-template/blob/main/CHANGELOG.md"
Documentation = "https://openfisca.org/doc"
Homepage = "https://github.com/openfisca/country-template"
Issues = "https://github.com/openfisca/country-template/issues"
Repository = "https://github.com/openfisca/country-template"

[tool.ruff]
target-version = "py39"
format.docstring-code-line-length = 72
format.docstring-code-format = true
lint.select = [ "ALL" ]
lint.ignore = [
    "ANN",
    "COM812",
    "D101",
    "D104",
    "ISC001",
    "N801",
    "N805",
    "N806",
    "PLR2004",
    "PTH100",
    "PTH118",
    "PTH120",
    "PTH123",
]
lint.pydocstyle.convention = "google"

[tool.ruff.lint.isort]
known-first-party = [ "openfisca_country_template" ]
combine-as-imports = true
force-single-line = false

[tool.pyproject-fmt]
column_width = 79
indent = 4
max_supported_python = "3.11"

[tool.pytest.ini_options]
addopts = "--exitfirst --showlocals --doctest-modules --disable-warnings --import-mode importlib"
testpaths = [ "openfisca_country_template/tests" ]
python_files = "**/*.py"
