###############################################################################
## Package description for Anaconda.org
## Warning : string PYPI_VERSION, PYPI_URL and PYPI_SHA256 are replaced by CI
## Keep them as is.
###############################################################################

{% set name = "OpenFisca-Country-Template" %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: PYPI_URL
  sha256: PYPI_SHA256

build:
  noarch: python
  number: 0
  script: "python3 -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6,<4.0
    - openfisca-core >=35.0.0,<36.0.0

test:
  imports:
    - country_template
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: openfisca-country-template

  - name: openfisca-country-template-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >=1.5.4, <2.0.0
        - flake8 >=3.8.0,<4.0.0
        - pylint >=2.6.0, <3.0.0
        - pycodestyle >=2.6.0, <3.0.0
        - {{ pin_subpackage('openfisca-country-template', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "OpenFisca tax and benefit system for Country-Template."
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the Country-Template module, to work with OpenFisca.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/country-template/
